#Configuration file

AccountClientNamespace: "OPENIO" #name of the Namespace file
endpoint: "" #IP address of the node containing the cluster access proxy
client: "admin" #name of the account owner of the containers
elasticsearchDomain: "192.168.1.100" #IP address of the domain on which the Elasticsearch server is launched
elasticsearchPort: "9200" #Elasticsearch database access port
elasticsearchFilenameAttribut: "file_name"

awsEndpointUrl: "http://192.168.1.115:6007"
awsSecretKey: 'DEMO_PASS'
awsAccessKeyId: 'demo:demo'
awsServiceName: 's3'
