#Configuration file

elasticsearchDomain: "192.168.1.104" #IP address of the domain on which the Elasticsearch server is launched
elasticsearchPort: "9200" #Elasticsearch database access port

awsEndpointUrl: "http://172.23.0.2:6007"
awsSecretKey: 'DEMO_PASS'
awsAccessKeyId: 'demo:demo'
awsServiceName: 's3'
